version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: note-system-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=admin_user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
