### CREATE note from server
PUT http://localhost:4000/notes/123e4567-e89b-12d3-a456-426614174003
Content-Type:application/json

{
  "title": "First Post updated",
  "content": "First Description"
}

###